FROM scratch

ADD 5de4d931374a09e8837eae014ca5601830b6a34c64c2569bdd3ced2a1cddc11f.tar.xz /
ADD 8bd9f63aeb02ca8ccc99ddb889e3ba737f62dd96678426693e9f1ce3406eccc6.tar.xz /
ADD c65a0f4fd9d87a97607b8ef7587df480fd77a232a1c0071f82ea37c3056479bc.tar.xz /
ADD fe422ddb3642d508a40dd0e256b752deec3ac98767709ba037872ce4fbceb400.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]

